name: build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docker/**'
jobs:
  build-n-publish:
    if: startsWith(github.ref, 'refs/tags')
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive 
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build a source tarball
      run: python setup.py sdist
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}